CREATE TABLE EMPLOYEE(
ID INT,
NAME VARCHAR(20),
DEPT VARCHAR(10),
SALARY INT);

SELECT * FROM EMPLOYEE;


INSERT INTO EMPLOYEE (ID,NAME,DEPT,SALARY) VALUES (1,'A1','D1',1000),(2,'A2','D1',2000),(3,'A3','D1',3000),
(4,'B1','D2',1000),(5,'B2','D2',2000),(6,'B3','D2',3000),(7,'C1','D3',1000),(8,'C2','D3',2000),(9,'C3','D3',3000);


--2nd Highest salary from EACH DEPARTMENT

SELECT * FROM (SELECT ID,NAME,DEPT,SALARY,row_number() 
OVER (PARTITION BY DEPT ORDER BY SALARY DESC) AS RANK
FROM EMPLOYEE) RANKING
WHERE RANK=2;


SELECT * FROM (SELECT ID,NAME,DEPT,SALARY,RANK() 
OVER (PARTITION BY DEPT ORDER BY SALARY DESC) AS RANK
FROM EMPLOYEE) RANKING
WHERE RANK=2;


SELECT * FROM (SELECT ID,NAME,DEPT,SALARY,DENSE_RANK() 
OVER (PARTITION BY DEPT ORDER BY SALARY DESC) AS RANK
FROM EMPLOYEE) RANKING
WHERE RANK=2;